### ISSUE TITLE
"Package is Invalid": Unable to install from Chrome web store

### ISSUE THREAD

**Issue by gtallen1187** [wildeyes/octodraft#2]
@wildeyes - I read about this extension and it seems ***awesome**, and I was super excited to install it and get it running.  However, after clicking the link in the readme and trying to install it from the webstore, I got strange popup that reads: `An error has occurred.  Package is invalid. Details: 'Could not load background script 'src/background.js'.'.`

Since I'm not really sure how else to help, I made a recording of exactly what I'm experiencing.  Please let me know if there's anything else I can do to help; I spend so much time writing comments, issues, and pr reviews in GitHub that this type of tool would be amazing for me, so I'm happy to help out in any way I can!

![4wqgpseawu](https://user-images.githubusercontent.com/4712768/46454514-88cbee00-c774-11e8-95a4-df6b03b76e59.gif)

**Comment by wildeyes** [comment]
Thank you for the issue, I'll check it out in two hours when I'm around a pc :)

**Comment by wildeyes** [comment]
@gtallen1187 Hey, uploaded a new version that downloads, care to check it out?

**Comment by gtallen1187** [comment]
It looks like this has been resolved.  Thank you for your help @wildeyes!
